### PR TITLE
New branching (master)

### PR DESCRIPTION
**Pull request by jotak**
Reorganize distribution process as per #11

### CODE REVIEW

**Comment by jotak** [comment]
@tsegismont can you have a look?

**Comment by tsegismont** [comment]
Looks good to me. Have you checked that changing the `wget`  target file actually switches to the release branch? Also, as discussed on IRC, please make sure with the Grafana team that they don't require the master branch to have a dist directory in order to show you in their plugins page.

**Comment by jotak** [comment]
Yes, the filename is directly related to the branch name I checked that on my repo.

I've asked yesterday the Grafana team about plugin distribution, now waiting for answer.

**Comment by jotak** [comment]
@tsegismont , the Grafana team doesn't seem in a hurry to answer my emails. Anyway, if they're really expecting to pull our plugin from master, we would just have to modify our branching so that current master becomes "develop", release becomes master, and ask contributors to send PR to develop. That wouldn't make a big change and would be exactly the same in terms of release process.

So I suggest to merge this anyway and eventually modify branches later.

**Comment by tsegismont** [comment]
+1 let's move on

2016-10-17 9:29 GMT+02:00 Joel Takvorian <notifications@github.com>:

**Pull request merged**
