### PR TITLE
HWKMETRICS-421 Hawkular Metrics versioned support

### PR DESCRIPTION
**Pull request by tsegismont**
Check version on graph panel initialization and then decide if we can
use the new POST method endpoints or fallback to a legacy call.

Legacy call uses deprecated data GET method endpoints, and applies rate
calculation on the client side. This is because old versions don't have
the rate endpoint for gauges.

### CODE REVIEW

**Comment by tsegismont** [comment]
@mwringe Hi, would you mind to have a look at this one? Thanks!

**Comment by spinolacastro** [comment]
Hello, some issue here (using Openshift's Hawkular ) which doesn't support POST method endpoints.

**Comment by mwringe** [comment]
@spinolacastro hmm, I assume you are using the latest origin metrics images. Do you know what exactly the error is? With the latest images, the POST endpoints for querying metrics should work (but POST to other endpoints to create metrics have been disabled by default, you can enable it by setting  USER_WRITE_ACCESS to true, but that should just be a work around until we figure out how to fix Hawkular Metrics)

**Comment by spinolacastro** [comment]
Hello, it's not the :latest since i had some serious issues regarding stability, so i'm running openshift/origin-metrics-hawkular-metrics:v1.2.0 image.

Here's the error, looks like it is trying to use POST to get metrics data:
captura de tela 2016-08-05 as 10 45 29

**Comment by mwringe** [comment]
Ah, ok, v1.2.0 is few months old (using Hawkular Metrics 0.14.0.Final) and I don't know if that had the POST methods at that point.

If it did have those POST methods, can you try using a token of a user that has edit permissions for the projects you are trying to access metrics from? A quick check with a cluster-admin level user would also be helpful here.

Using POST methods for performing queries like this is usually not the best idea. The old configuration assumed that a POST method would be for modifying data and required edit permission for the project in order for it to succeed. In 0.18 we properly handle the POST queries are only requiring read access.

**Comment by burmanm** [comment]
Hawkular-Metrics 0.17.0 was the first version to have these POST methods (for Grafana - otherwise Grafana can't read metricIds with slash in them).

**Comment by psteyn** [comment]
Thanks so much @tsegismont 
This also helped me get the plugin working with openshift-metrics v1.2.0.

**Comment by spinolacastro** [comment]
I have some news, i got hawkular 0.18.4 and installed oficial grafana plugin.
I want to be able to plot graphs from '_system' tenant, not sure what i'm missing, but i can't it on the tenant list when adding a new dashboard:


captura de tela 2016-09-15 as 10 06 39


Dataset Type: Hawkular

Access: proxy
Hawkular Settings:
Tenant: _system

**Comment by tsegismont** [comment]
Can you elaborate? This is not a tenant list, this is a datasource list. You need to configure a datasource pointing for the _system tenant and then you can select it here.

**Comment by spinolacastro** [comment]
Sorry, i got confused with the names and realized that my cassandra cluster was timing out to list _system metrics.

**Comment by jotak** [comment]
@tsegismont I will test it asap. Since it conflicts with my other PR I'd like to merge this one first then I'll rebase the others.

**Comment by tsegismont** [comment]
Thank you :-)

2016-09-22 17:48 GMT+02:00 Joel Takvorian <notifications@github.com>:

**Comment by jotak** [comment]
Looks good to me.
Tested with hawkular current dev version (with POST endpoints) and hawkular 0.16 (without POST)
(with the known limitation on old versions that metric names must not contain "/")

**Pull request merged**
