### PR TITLE
Updated to 1.0.7

### PR DESCRIPTION
**Pull request by garethahealy**
The archive/release.zip no longer exists, so the OCP build fails.

### CODE REVIEW

**Comment by jotak** [comment]
Really?
I just tried to download https://github.com/hawkular/hawkular-grafana-datasource/archive/release.zip ... and succeeded.

**Comment by garethahealy** [comment]
I keep getting a 500 error:

> localhost:hawkular-grafana-datasource garethah$ curl -L https://github.com/hawkular/hawkular-grafana-datasource/archive/release.zip
> 500: Internal Server Error

**Comment by jotak** [comment]
Yep, I have randomly sometimes an error, sometimes success.

**Comment by garethahealy** [comment]
Closing. Putting issue down to github being flakey.

**Pull request closed without merging**
