### PR TITLE
Adding token authentification

### PR DESCRIPTION
**Pull request by Lunik**
Hi !
I use Hawkular metrics on  my OpenShift cluster and the authetification is made by passing the OpenShift token in header of the request.

I don't realy know if the modification that I made are good but this is the idea.

### CODE REVIEW

**Comment by tsegismont** [comment]
Overall the changes look good to me. I know Openshift Metrics server
supports basic auth as well. But I don't know why one would use token auth
instead of it. Perhaps @mwringe has an idea?

2016-06-10 10:39 GMT+02:00 Lunik <notifications@github.com>:

**Comment by Lunik** [comment]
It is mentioned into the [OpenShift Metrics documentation](https://github.com/openshift/origin-metrics/blob/master/docs/hawkular_metrics.adoc#authorization).

```
curl -H "Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
       -H "Hawkular-tenant: _system"
       -X GET https://hawkular-metrics.example.com/hawkular/metrics/metrics
```

**Comment by mwringe** [comment]
Token auth is for user authentication, and is what you should almost always be using.

The basic auth is used to bypass the normal authentication for trusted services. In our case its meant only for Heapster. It should only be used by trusted components which should have root level access to metrics. Ideally this should be replaced with certificate based authentication in the future.

For something like grafana, it should be restricted to token authentication. This would allow multiple users to potentially login and only have access to metrics for which they have authorization. If you were to use basic auth, then it means only a root level admin would ever be able to use it.

**Comment by tsegismont** [comment]
Thank you @Lunik !

**Comment by Lunik** [comment]
You're welcome :smile:

**Pull request merged**
