### PR TITLE
HWKMETRICS-410 Grafana datasource plugin can't read metrics collected by

### PR DESCRIPTION
**Pull request by tsegismont**
Hawkular agent

Use the new POST endpoints introduced in HWKMETRICS-393.

### CODE REVIEW

**Comment by burmanm** [comment]
LGTM

**Comment by tsegismont** [comment]
@pilhuhn could you merge and give @burmanm the proper grants? Thanks!

**Comment by pilhuhn** [comment]
On 1 Jul 2016, at 11:10, Thomas Segismont wrote:

> @pilhuhn could you merge and give @burmanm the proper grants? Thanks!

Both done.

**Comment by tsegismont** [comment]
Thanks!

**Pull request merged**
