### PR TITLE
Add a Dockerfile

### PR DESCRIPTION
**Pull request by yaacov**
Add a minimalistic docker file for testing

### CODE REVIEW

**Comment by yaacov** [comment]
@simon3z @pilhuhn please review

**Comment by theute** [comment]
@jotak Maybe something you could review and merge if it's ok

**Comment by simon3z** [comment]
cc @bazulay

**Comment by jotak** [comment]
Thank you @yaacov

**Comment by yaacov** [comment]
@jotak Thank you :-)

**Pull request merged**
