### PR TITLE
Changes for publishing to Grafana.net

### PR DESCRIPTION
**Pull request by daniellee**
Here are three smalls changes. The first two need to be merged so that it can be published to Grafana.net and installed with the Grafana CLI.

1. First commit changes the plugin name to `hawkular-datasource'
2. Second commit checks in the dist directory. Grafana does not dynamically build plugins. The
dist directory needs to be published with the plugin to be picked up by Grafana when it starts up.
3. A css change that makes the input field wider when searching by name

Great work on the plugin!

### CODE REVIEW

**Comment by pilhuhn** [comment]
Thank you @daniellee !!

**Comment by jotak** [comment]
ouch :-/ I wouldn't have done it this way. The dist directory was intentionally removed from master, but it's built in "release" branch. I've asked grafana team about that because I knew they were expecting "dist". We should avoid having the build in the same branch than the development versions.

**Comment by jotak** [comment]
@daniellee , I sent an email to plugins@grafana.net 3 weeks ago, entitled "Questions before submitting a plugin". I didn't receive any response, is this email address dead?

My mail was precisely about how you pick up the "dist" directory, and if we could provide an url to it (it's actually on github as well, but in "release" instead of "master".
If you expect to find it on master, my plan was simply to rename this "master" branch to "develop", and "release" to "master", so you'd be fine with the distribution.

So, if no objection, I'll revert the commit that adds 'dist' to master and do my branch renaming.

**Comment by daniellee** [comment]
@jotak we just need a commit hash to publish, it can be on any branch. So feel free to revert this and set it up however you want it. Just keep the change with the plugin id (from hawkular to hawkular-datasource) in the plugin.json.

For every new version, you first change the version in the plugin.json and then submit the commit hash to this repo: https://github.com/grafana/grafana-plugin-repository

Sorry about not replying. Just saw your ticket in our system.

**Comment by jotak** [comment]
@daniellee ok, sounds great. So I've just released our 1.0.4 with your changes on plugin.json and the css. I've also added some documentation in the readme file. The sha1 is 6f0e89720d7cb8d7f4f8aa5dc6c679a2579060ea

So I'm going to create a PR on grafana-plugin-repository

**Comment by jotak** [comment]
FYI https://github.com/grafana/grafana-plugin-repository/pull/55

**Pull request merged**
