### PR TITLE
Updated docker image to be not based on upstream grafana

### PR DESCRIPTION
**Pull request by garethahealy**
As per [1] the grafana base docker image uses volumes for plugins, etc and grafana which causes issues. They also use "gosu" which causes problems in OCP when running under the restricted SCC (default).

Have also created 2 OCP templates to make it easier to consume the docker image.

[1] https://github.com/hawkular/hawkular-grafana-datasource/issues/40

### CODE REVIEW

**Comment by jotak** [comment]
I'm testing it (sorry for the delay!)
Do we still need the build.sh script, or can it be removed?

**Comment by jotak** [comment]
LGTM, if you could just delete build.sh now it's obsolete

**Comment by garethahealy** [comment]
As requested.

**Comment by jotak** [comment]
Thanks @garethahealy

**Pull request merged**
